migrate app container health check to reuse compose file healthcheck

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -197,7 +197,13 @@ jobs:
       - name: Start containers
         working-directory: tests
         run: |
-          docker compose up -d --quiet-pull --wait
+          set -e
+          if ! docker compose up -d --quiet-pull --wait; then
+            echo "Containers failed to become healthy."
+            echo "Printing logs for nomad_oasis_app: "
+            docker logs nomad_oasis_app
+            exit 1
+          fi
 
       - name: Install uv
         uses: astral-sh/setup-uv@v5
@@ -211,35 +217,30 @@ jobs:
       - name: Install dependencies
         run: uv sync --all-extras
 
-      - name: Health check
+      - name: Jupyter health check
         run: |
           #!/bin/bash
           set -e # Exit immediately if a command exits with a non-zero status.
 
-          secs=300                           # Set interval (duration) in seconds.
-          endTime=$(( $(date +%s) + secs )) # Calculate end time.
-
-          check_app_health() {
-              curl -s localhost:8000/-/health > /dev/null
-          }
+          secs=300                           # Set timeout in seconds.
+          endTime=$(( $(date +%s) + secs ))  # Calculate end time.
 
           check_jupyter_health() {
               curl -s localhost:8888/ > /dev/null
           }
 
-          while [ $(date +%s) -lt $endTime ]; do  # Loop until interval has elapsed.
-            if check_app_health && check_jupyter_health; then
-                echo "Both App and Jupyter health endpoints are responding correctly."
+          while [ $(date +%s) -lt $endTime ]; do  # Loop until timeout has elapsed.
+            if check_jupyter_health; then
+                echo "Jupyter health endpoint is responding correctly."
                 exit 0
             else
-                echo "The App or Jupyter health endpoint is not responding. Retrying in 10 seconds..."
+                echo "The Jupyter health endpoint is not responding. Retrying in 10 seconds..."
                 sleep 10
             fi
           done
 
-          echo "Timeout reached. The App or Jupyter health endpoint did not respond within 5 minutes."
+          echo "Timeout reached. The Jupyter health endpoint did not respond within ${secs} seconds."
           echo "Fetching Docker logs for debugging..."
-          docker logs app  # Output logs from the app container
           docker logs jupyter  # Output logs from the Jupyter container
           exit 1
 
