Add plugin unit tests and example upload tests (#51)
* Plugin tests (#5)

* Run plugin unit tests

* Temp fix for git ref

* Upgrade packages

* Run tests in parallel

* Update requirements

* Disable fail fast

* Use uv version 0.6

* Add example upload tests step

* Fix version

* Python version variable

* Require updated lockfile for tests

* Skip more plugins

* Use docker image for app

* Add setuptools as a dependency

* Add basic example upload test (#6)

* Debug

* Add local keycloak

* Add basic test

* Uncomment other steps

* Remove some comments

* Parametrize example upload tests (#7)

* Add dependebot support (#8)

* Update lockfile

* Add dependabot.yml

* Fix dep-bot

* Change requires python to >= 3.10

* Update lockfile

* Push images from branches (#11)

* Use fixed version for nomad keycloak

* Disable pytest warnings and disable repo initialisation for dependebot commits

* Disable automatic upgrades for nomad-lab package

* Skip pynxtools_igor tests

* Bump pynxtools[convert] from 0.9.1 to 0.9.3 in the python group (#10)

* Bump pynxtools[convert] from 0.9.1 to 0.9.3 in the python group

Bumps the python group with 1 update: [pynxtools[convert]](https://github.com/FAIRmat-NFDI/pynxtools).


Updates `pynxtools[convert]` from 0.9.1 to 0.9.3
- [Release notes](https://github.com/FAIRmat-NFDI/pynxtools/releases)
- [Commits](https://github.com/FAIRmat-NFDI/pynxtools/compare/v0.9.1...v0.9.3)

---
updated-dependencies:
- dependency-name: pynxtools[convert]
  dependency-type: direct:production
  update-type: version-update:semver-patch
  dependency-group: python
...

Signed-off-by: dependabot[bot] <support@github.com>

* Update lockfile

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: github-actions <github-actions@github.com>

* Use app image

* Assert no errors or warnings in example upload processing (#12)

* Bump jupyter/datascience-notebook from 2025-01-13 to 2025-03-10 (#13)

* Eager check for errors and warnings

* Check entries for errors (#14)

* Run plugin tests via nomad-plugin-tests package (#16)

* Allow skipping plugin example tests (#18)

* Bump jupyter/datascience-notebook from 2025-03-10 to 2025-03-17 (#17)

Bumps jupyter/datascience-notebook from 2025-03-10 to 2025-03-17.

---
updated-dependencies:
- dependency-name: jupyter/datascience-notebook
  dependency-type: direct:production
...

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Refetch token when response is 404 (#15)

* Update docs (#19)

* Add docs for tests and dependabot

* Relative link for docker publish yml

* Log output if app startup fails in example tests (#20)

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: github-actions <github-actions@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -13,6 +13,19 @@ on:
 
 env:
   REGISTRY: ghcr.io
+  UV_VERSION: 0.6
+  PYTHON_VERSION: 3.12
+  # If you want to skip the tests for some plugins, add them to the list below
+  PLUGIN_TESTS_PLUGINS_TO_SKIP: |
+    workflowparsers
+    nomad_porous_materials
+    simulationworkflowschema
+    databaseparsers
+    soapnormalizer
+    eelsdbparser
+    atomisticparsers
+    nomad_aitoolkit
+    pynxtools_igor
 
 permissions:
   contents: write
@@ -36,14 +49,14 @@ jobs:
       - name: Install uv
         uses: astral-sh/setup-uv@v5
         with:
-          version: "==0.5"
+          version: ${{ env.UV_VERSION }}
 
       - uses: actions/setup-python@v5
         with:
-          python-version: "3.12"
+          python-version: ${{ env.PYTHON_VERSION }}
 
       - name: Update lock file
-        run: uv lock --upgrade-package nomad-lab
+        run: uv lock
 
       # Commits any changes made to the lockfile
       - name: Commit lock file changes
@@ -63,8 +76,45 @@ jobs:
           echo "SCM version: $SCM_VERSION"
           echo "scm_version=$SCM_VERSION" >> "$GITHUB_OUTPUT"
 
-  # Job 2: Build and Push Docker Image
-  docker-publish:
+  # Job 2: Run unit tests for all of the plugin
+  plugin_unit_tests:
+    name: Run plugin unit tests
+    needs: update-lockfile
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        group: [1, 2]
+    env:
+      PLUGIN_TESTS_CI_NODE_TOTAL: 2
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.head_ref || github.ref_name }}
+          submodules: true
+
+      - name: Install uv
+        uses: astral-sh/setup-uv@v5
+        with:
+          version: ${{ env.UV_VERSION }}
+
+      - uses: actions/setup-python@v5
+        with:
+          python-version: ${{ env.PYTHON_VERSION }}
+
+      - name: Run plugin tests
+        env:
+          PLUGIN_TESTS_CI_NODE_INDEX: ${{ matrix.group }}
+        run: |
+          # replace the yaml list with a string, use a `,` to separate the plugins
+          PLUGINS_STRING=$(echo "$PLUGIN_TESTS_PLUGINS_TO_SKIP" | tr '\n' ',' | sed 's/,$//')
+          uv run \
+            --extra plugins \
+            --with "nomad-plugin-tests==0.1" \
+            nomad-plugin-tests --plugins-to-skip "$PLUGINS_STRING"
+
+  # Job 3: Build and Push Docker Image
+  build:
     name: Build Docker Image
     runs-on: ubuntu-latest
     needs: update-lockfile
@@ -101,10 +151,83 @@ jobs:
         uses: docker/build-push-action@v5
         with:
           context: .
-          build-args: "SETUPTOOLS_SCM_PRETEND_VERSION_FOR_NOMAD_DISTRIBUTION=${{ env.SETUPTOOLS_SCM_PRETEND_VERSION_FOR_NOMAD_DISTRIBUTION }}"
+          build-args: |
+            SETUPTOOLS_SCM_PRETEND_VERSION_FOR_NOMAD_DISTRIBUTION=${{ env.SETUPTOOLS_SCM_PRETEND_VERSION_FOR_NOMAD_DISTRIBUTION }}
+            UV_VERSION=${{ env.UV_VERSION }}
+            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
           cache-from: type=gha
           cache-to: type=gha,mode=max
           target: ${{ matrix.service == 'jupyter' && 'jupyter' || 'final' }}
-          push: ${{ github.event_name != 'pull_request' }}
+          push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
+
+      - name: Set output only for app service
+        if: matrix.service == 'app'
+        run: echo "APP_IMAGE=${{ steps.meta.outputs.tags }}" >> $GITHUB_ENV
+
+    outputs:
+      app_image: ${{ env.APP_IMAGE }}
+
+  # Job 4: Run example upload tests
+  example_upload_tests:
+    name: Run example upload tests
+    needs: build
+    runs-on: ubuntu-latest
+    env:
+      APP_IMAGE: ${{ needs.build.outputs.app_image }}
+
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.head_ref || github.ref_name }}
+          submodules: true
+      - name: Start containers
+        working-directory: tests
+        run: |
+          docker compose up -d --quiet-pull
+
+      - name: Install uv
+        uses: astral-sh/setup-uv@v5
+        with:
+          version: ${{ env.UV_VERSION }}
+
+      - uses: actions/setup-python@v5
+        with:
+          python-version: ${{ env.PYTHON_VERSION }}
+
+      - name: Install dependencies
+        run: uv sync --all-extras
+
+      - name: Health check
+        run: |
+          #!/bin/bash
+          set -e # Exit immediately if a command exits with a non-zero status.
+
+          secs=180                           # Set interval (duration) in seconds.
+          endTime=$(( $(date +%s) + secs )) # Calculate end time.
+
+          check_health() {
+              curl -s localhost:8000/-/health > /dev/null
+          }
+
+          while [ $(date +%s) -lt $endTime ]; do  # Loop until interval has elapsed.
+               if check_health; then
+                echo "Health endpoint is responding correctly."
+                exit 0
+              else
+                echo "Health endpoint is not responding. Retrying in 10 seconds..."
+                sleep 10
+              fi
+          done
+
+          echo "Timeout reached. Health endpoint did not respond within 3 minutes."
+          echo "Fetching Docker logs for debugging..."
+          docker logs app  # Output logs from the app container
+          exit 1
+
+      - name: Run tests
+        working-directory: tests
+        run: |
+          export PLUGINS_STRING=$(echo "$PLUGIN_TESTS_PLUGINS_TO_SKIP" | tr '\n' ',' | sed 's/,$//')
+          uv run --extra plugins pytest -p no:warnings -sv
